const GLOBAL_ACTIONS = {
  SET_TOPIC_ID: "SET_TOPIC_ID",
  SET_EMOTION: "SET_EMOTION",
  SET_AI_RESPONSES: "SET_AI_RESPONSES",
  SET_LOADING_NET: "SET_LOADING_NET",
};

export default GLOBAL_ACTIONS;
